config/routes.rb
Rails.application.routes.draw do
  resources :medicals
  resources :medical_histories
  resources :diaries
  resources :specialities
  resources :pets
  resources :test2s
  root 'static_pages#index'
  resources :species
  resources :responsibles
  resources :locations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :medical
  belongs_to :pet
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :pacient
end

app/models/medical.rb
class Medical < ApplicationRecord
  belongs_to :speciality
end

app/models/medical_history.rb
class MedicalHistory < ApplicationRecord
  belongs_to :diary
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :location
  belongs_to :responsible
  belongs_to :species
end

app/models/responsible.rb
class Responsible < ApplicationRecord
    has_many :pacient
end

app/models/speciality.rb
class Speciality < ApplicationRecord
  belongs_to :location
end

app/models/species.rb
class Species < ApplicationRecord
    has_many :pacient
end

app/models/test2.rb
class Test2 < ApplicationRecord
  belongs_to :location
  belongs_to :responsible
  belongs_to :species
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: %i[ show edit update destroy ]

  # GET /diaries or /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1 or /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries or /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to diary_url(@diary), notice: "Diary was successfully created." }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1 or /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to diary_url(@diary), notice: "Diary was successfully updated." }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1 or /diaries/1.json
  def destroy
    @diary.destroy

    respond_to do |format|
      format.html { redirect_to diaries_url, notice: "Diary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def diary_params
      params.require(:diary).permit(:medical_id, :pet_id, :horario, :fecha)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]

  # GET /pets or /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1 or /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:location_id, :responsible_id, :species_id, :nombre)
    end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  before_action :set_species, only: %i[ show edit update destroy ]

  # GET /species or /species.json
  def index
    @species = Species.all
  end

  # GET /species/1 or /species/1.json
  def show
  end

  # GET /species/new
  def new
    @species = Species.new
  end

  # GET /species/1/edit
  def edit
  end

  # POST /species or /species.json
  def create
    @species = Species.new(species_params)

    respond_to do |format|
      if @species.save
        format.html { redirect_to species_url(@species), notice: "Species was successfully created." }
        format.json { render :show, status: :created, location: @species }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /species/1 or /species/1.json
  def update
    respond_to do |format|
      if @species.update(species_params)
        format.html { redirect_to species_url(@species), notice: "Species was successfully updated." }
        format.json { render :show, status: :ok, location: @species }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /species/1 or /species/1.json
  def destroy
    @species.destroy

    respond_to do |format|
      format.html { redirect_to species_index_url, notice: "Species was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_species
      @species = Species.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def species_params
      params.require(:species).permit(:raza, :genero, :edad, :esterilizado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/medicals_helper.rb
module MedicalsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

app/helpers/specialities_helper.rb
module SpecialitiesHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/test2s_helper.rb
module Test2sHelper
end

app/views/diaries/_diary.html.erb
<body class="bg-gray-100 font-sans leading-normal tracking-normal">
    <!--Container-->
    <div class="container w-full mx-auto pt-20">

        <div class="w-full px-4 md:px-0 md:mt-8 mb-16 text-gray-800 leading-normal">

          <div class="flex flex-col">
            <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                  <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    <%= link_to 'Nuevo Medico', new_medical_path %>
                  </button>
                  <table class="min-w-full text-center">
                    <thead class="border-b bg-gray-800">
                      <tr>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          #
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Diario ID
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Medico
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Mascota
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Horario
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Fecha
                        </th>
                      </tr>
                    </thead class="border-b">
                    <tbody>
                      <p id="notice"><%= notice %></p>
                      <tr class="bg-white border-b">
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= diary.id %></td>
                        <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                          <%= diary.medical.nombre %>
                        </td>
                        <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                          <%= diary.pet.nombre %>
                        </td>
                        <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                          <%= diary.horario %>
                        </td>
                        <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                          <%= diary.fecha %>
                        </td>
                      </tr class="bg-white border-b">
                    </tbody>
                  </table>
                </div>
              </div>
  </div>
</div>

            <!--Console Content-->

            
          

            <!--Divider-->
            <hr class="border-b-2 border-gray-400 my-8 mx-4">

            <!--/ Console Content-->

        </div>


    </div>
    <!--/container-->

    <script>
    /*Toggle dropdown list*/
    /*https://gist.github.com/slavapas/593e8e50cf4cc16ac972afcbad4f70c8*/

    var userMenuDiv = document.getElementById("userMenu");
    var userMenu = document.getElementById("userButton");

    var navMenuDiv = document.getElementById("nav-content");
    var navMenu = document.getElementById("nav-toggle");

    document.onclick = check;

    function check(e) {
        var target = (e && e.target) || (event && event.srcElement);

        //User Menu
        if (!checkParent(target, userMenuDiv)) {
            // click NOT on the menu
            if (checkParent(target, userMenu)) {
                // click on the link
                if (userMenuDiv.classList.contains("invisible")) {
                    userMenuDiv.classList.remove("invisible");
                } else { userMenuDiv.classList.add("invisible"); }
            } else {
                // click both outside link and outside menu, hide menu
                userMenuDiv.classList.add("invisible");
            }
        }

        //Nav Menu
        if (!checkParent(target, navMenuDiv)) {
            // click NOT on the menu
            if (checkParent(target, navMenu)) {
                // click on the link
                if (navMenuDiv.classList.contains("hidden")) {
                    navMenuDiv.classList.remove("hidden");
                } else { navMenuDiv.classList.add("hidden"); }
            } else {
                // click both outside link and outside menu, hide menu
                navMenuDiv.classList.add("hidden");
            }
        }

    }

    function checkParent(t, elm) {
        while (t.parentNode) {
            if (t == elm) { return true; }
            t = t.parentNode;
        }
        return false;
    }
    </script>

</body>

</html>

app/views/diaries/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing diary</h1>

  <%= render "form", diary: @diary %>

  <%= link_to "Show this diary", @diary, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to diaries", diaries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/diaries/index.html.erb
<body class="bg-gray-100 font-sans leading-normal tracking-normal">
<!--Container-->
<div class="container w-full mx-auto pt-20">

    <nav class="bg-white border-gray-200 dark:bg-gray-900">
        <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl px-4 md:px-6 py-2.5">
            <a href="https://flowbite.com" class="flex items-center">
                <img src="https://flowbite.com/docs/images/logo.svg" class="h-6 mr-3 sm:h-9" alt="Flowbite Logo" />
                <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Medicos</span>
            </a>
        </div>
    </nav>
    <nav class="bg-gray-50 dark:bg-gray-700">
        <div class="max-w-screen-xl px-4 py-3 mx-auto md:px-6">
            <div class="flex items-center">
                <ul class="flex flex-row mt-0 mr-6 space-x-8 text-sm font-medium">
                    <li>
                        <%= link_to "Especialidades", specialities_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                    </li>
                    <li>
                         <%= link_to 'Historial Medico', medical_histories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                    </li>
                    <li>
                        <%= link_to 'Diario', diaries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                    </li>
                    
                </ul>
            </div>
        </div>
    </nav>


    <div class="w-full px-4 md:px-0 md:mt-8 mb-16 text-gray-800 leading-normal">

      <div class="flex flex-col">
        <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
            <div class="overflow-hidden">
              <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
               <%= link_to 'Registra Un Calendario', new_diary_path %>
              </button>
              </a>
              <table class="min-w-full text-center">
                <thead class="border-b bg-gray-800">
                  <tr>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      #
                    </th>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      Diario ID
                    </th>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      Medico
                    </th>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      Mascota
                    </th>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      Horario
                    </th>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      Fecha
                    </th>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      Mostrar
                    </th>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      Editar
                    </th>
                  </tr>
                </thead class="border-b">
                <tbody>
                  <p id="notice"><%= notice %></p>
                  <% @diaries.each do |diary| %>
                    <tr class="bg-white border-b">
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= diary.id %></td>
                      <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                        <%= diary.medical.nombre %>
                      </td>
                      <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                        <%= diary.pet.nombre %>
                      </td>
                      <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                        <%= diary.horario %>
                      </td>
                       <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                        <%= diary.fecha %>
                      </td>
                      <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                        <%= link_to 'MOSTRAR', diary,class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                      </td>
                      <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                        <%= link_to 'Editar', edit_pet_path(diary), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                      </td>
                  
                    </tr class="bg-white border-b">
                  <% end %>  
                </tbody>
              </table>
            </div>
          </div>
</div>
</div>

app/views/diaries/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New diary</h1>

  <%= render "form", diary: @diary %>

  <%= link_to 'Back to diaries', diaries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/diaries/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @diary %>

    <%= link_to 'Edit this diary', edit_diary_path(@diary), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this diary', diary_path(@diary), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to diaries', diaries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/pets/_pet.html.erb
<div id="<%= dom_id pet %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Location:</strong>
    <%= pet.location_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Responsible:</strong>
    <%= pet.responsible_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Species:</strong>
    <%= pet.species_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Nombre:</strong>
    <%= pet.nombre %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this pet", pet, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this pet', edit_pet_path(pet), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/pets/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing pet</h1>

  <%= render "form", pet: @pet %>

  <%= link_to "Show this pet", @pet, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to pets", pets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pets/index.html.erb
<body class="bg-gray-100 font-sans leading-normal tracking-normal">
    <!--Container-->
    <div class="container w-full mx-auto pt-20">

      <nav class="bg-white border-gray-200 dark:bg-gray-900">
            <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl px-4 md:px-6 py-2.5">
                <a href="https://flowbite.com" class="flex items-center">
                    <img src="https://flowbite.com/docs/images/logo.svg" class="h-6 mr-3 sm:h-9" alt="Flowbite Logo" />
                    <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Mascota</span>
                </a>
            </div>
        </nav>
        <nav class="bg-gray-50 dark:bg-gray-700">
            <div class="max-w-screen-xl px-4 py-3 mx-auto md:px-6">
                <div class="flex items-center">
                    <ul class="flex flex-row mt-0 mr-6 space-x-8 text-sm font-medium">
                        <li>
                            <%= link_to "Mascotas", pets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                        </li>
                        <li>
                            <%= link_to 'Especies', species_index_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                        </li>
                       
                        
                    </ul>
                </div>
            </div>
        </nav>

        <div class="w-full px-4 md:px-0 md:mt-8 mb-16 text-gray-800 leading-normal">

          <div class="flex flex-col">
            <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                  <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                   <%= link_to 'Registra Una Mascota', new_pet_path %>
                  </button>
                  </a>
                  <table class="min-w-full text-center">
                    <thead class="border-b bg-gray-800">
                      <tr>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          #
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Vterinaria
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Dueño
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Nombre
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Especie
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Mostrar
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Editar
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Eliminar
                        </th>
                      </tr>
                    </thead class="border-b">
                    <tbody>
                      <p id="notice"><%= notice %></p>
                      <% @pets.each do |pet| %>
                        <tr class="bg-white border-b">
                          <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">1</td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= pet.location.nombre %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= pet.responsible.nombre %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= pet.nombre %>
                          </td>
                           <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= pet.species.raza %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= link_to 'Show', pet %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= link_to 'Edit this pet', edit_pet_path(pet), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                           <%= button_to 'Destroy this pet', pet_path(pet), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
                          </td>
                        </tr class="bg-white border-b">
                      <% end %>  
                    </tbody>
                  </table>
                </div>
              </div>
  </div>
</div>

app/views/pets/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New pet</h1>

  <%= render "form", pet: @pet %>

  <%= link_to 'Back to pets', pets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pets/show.html.erb
<body class="bg-gray-100 font-sans leading-normal tracking-normal">
    <!--Container-->
    <div class="container w-full mx-auto pt-20">

        <div class="w-full px-4 md:px-0 md:mt-8 mb-16 text-gray-800 leading-normal">

          <div class="flex flex-col">
            <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                  <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    <%= link_to 'New Location', new_location_path %>
                  </button>
                  <table class="min-w-full text-center">
                    <thead class="border-b bg-gray-800">
                      <tr>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          #
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Localidad
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Responsable
                        </th>
                         <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Raza
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Nombre
                        </th>
                      </tr>
                    </thead class="border-b">
                    <tbody>
                      <p id="notice"><%= notice %></p>
                        <tr class="bg-white border-b">
                          <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">1</td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= @pet.location.nombre %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= @pet.responsible.nombre %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= @pet.species.raza %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= @pet.nombre %>
                          </td>
  
                        </tr class="bg-white border-b">
                    </tbody>
                  </table>
                </div>
              </div>
  </div>
</div>

            <!--Console Content-->

            
          

            <!--Divider-->
            <hr class="border-b-2 border-gray-400 my-8 mx-4">
             <button class="ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium">
              <%= link_to 'Editar', edit_pet_path(@pet),  class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"  %>
            </button>

            <button class="ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium">
              <%= button_to 'Eliminar', pets_path(@pet), method: :delete,  class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"  %>
            </button>

            <button class="ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium">
            <%= link_to 'Atras', pets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
            </button>

            <!--/ Console Content-->

        </div>


    </div>
    <!--/container-->

    <script>
    /*Toggle dropdown list*/
    /*https://gist.github.com/slavapas/593e8e50cf4cc16ac972afcbad4f70c8*/

    var userMenuDiv = document.getElementById("userMenu");
    var userMenu = document.getElementById("userButton");

    var navMenuDiv = document.getElementById("nav-content");
    var navMenu = document.getElementById("nav-toggle");

    document.onclick = check;

    function check(e) {
        var target = (e && e.target) || (event && event.srcElement);

        //User Menu
        if (!checkParent(target, userMenuDiv)) {
            // click NOT on the menu
            if (checkParent(target, userMenu)) {
                // click on the link
                if (userMenuDiv.classList.contains("invisible")) {
                    userMenuDiv.classList.remove("invisible");
                } else { userMenuDiv.classList.add("invisible"); }
            } else {
                // click both outside link and outside menu, hide menu
                userMenuDiv.classList.add("invisible");
            }
        }

        //Nav Menu
        if (!checkParent(target, navMenuDiv)) {
            // click NOT on the menu
            if (checkParent(target, navMenu)) {
                // click on the link
                if (navMenuDiv.classList.contains("hidden")) {
                    navMenuDiv.classList.remove("hidden");
                } else { navMenuDiv.classList.add("hidden"); }
            } else {
                // click both outside link and outside menu, hide menu
                navMenuDiv.classList.add("hidden");
            }
        }

    }

    function checkParent(t, elm) {
        while (t.parentNode) {
            if (t == elm) { return true; }
            t = t.parentNode;
        }
        return false;
    }
    </script>

</body>

</html>