config/routes.rb
Rails.application.routes.draw do
  resources :medicals
  resources :medical_histories
  resources :diaries
  resources :specialities
  resources :pets
  resources :test2s
  root 'static_pages#index'
  resources :species
  resources :responsibles
  resources :locations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :medical
  belongs_to :pet
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :pacient
end

app/models/medical.rb
class Medical < ApplicationRecord
  belongs_to :speciality
end

app/models/medical_history.rb
class MedicalHistory < ApplicationRecord
  belongs_to :diary
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :location
  belongs_to :responsible
  belongs_to :species
end

app/models/responsible.rb
class Responsible < ApplicationRecord
    has_many :pacient
end

app/models/speciality.rb
class Speciality < ApplicationRecord
  belongs_to :location
end

app/models/species.rb
class Species < ApplicationRecord
    has_many :pacient
end

app/models/test2.rb
class Test2 < ApplicationRecord
  belongs_to :location
  belongs_to :responsible
  belongs_to :species
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]

  # GET /pets or /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1 or /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:location_id, :responsible_id, :species_id, :nombre)
    end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  before_action :set_species, only: %i[ show edit update destroy ]

  # GET /species or /species.json
  def index
    @species = Species.all
  end

  # GET /species/1 or /species/1.json
  def show
  end

  # GET /species/new
  def new
    @species = Species.new
  end

  # GET /species/1/edit
  def edit
  end

  # POST /species or /species.json
  def create
    @species = Species.new(species_params)

    respond_to do |format|
      if @species.save
        format.html { redirect_to species_url(@species), notice: "Species was successfully created." }
        format.json { render :show, status: :created, location: @species }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /species/1 or /species/1.json
  def update
    respond_to do |format|
      if @species.update(species_params)
        format.html { redirect_to species_url(@species), notice: "Species was successfully updated." }
        format.json { render :show, status: :ok, location: @species }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /species/1 or /species/1.json
  def destroy
    @species.destroy

    respond_to do |format|
      format.html { redirect_to species_index_url, notice: "Species was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_species
      @species = Species.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def species_params
      params.require(:species).permit(:raza, :genero, :edad, :esterilizado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/medicals_helper.rb
module MedicalsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

app/helpers/specialities_helper.rb
module SpecialitiesHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/test2s_helper.rb
module Test2sHelper
end

app/views/species/_form.html.erb
<body class="font-mono bg-gray-400">
		<!-- Container -->
		<div class="container mx-auto">
			<div class="flex justify-center px-6 my-12">
				<!-- Row -->
				<div class="w-full xl:w-3/4 lg:w-11/12 flex">
					<!-- Col -->
					<div
						class="w-full h-auto bg-gray-400 hidden lg:block lg:w-5/12 bg-cover rounded-l-lg"
						style="background-image: url('https://source.unsplash.com/Mv9hjnEUHR4/600x800')"
					></div>
					<!-- Col -->
					<div class="w-full lg:w-7/12 bg-white p-5 rounded-lg lg:rounded-l-none">
						<h3 class="pt-4 text-2xl text-center">Registra Una Raza</h3>
            <%= form_with(model: species) do |form| %>
              <% if species.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(species.errors.count, "error") %> prohibited this location from being saved:</h2>

                  <ul>
                    <% species.errors.each do |error| %>
                      <li><%= error.full_message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="mb-4 md:flex md:justify-between">
                <div class="mb-4 md:mr-2 md:mb-0">
                  <label class="block mb-2 text-sm font-bold text-gray-700" for="firstName">
                    <%= form.label :raza %>
                  </label>
                  <%= form.text_field :raza ,class: "w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"%>
                </div>
                <div class="md:ml-2">
                  <label class="block mb-2 text-sm font-bold text-gray-700" for="lastName">
                    <%= form.label :genero %>
                  </label>
                  <%= form.text_field :genero , class: "w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"%>
                </div>
              </div>
              <div class="mb-4 md:flex md:justify-between">
                <div class="mb-4 md:mr-2 md:mb-0">
                  <label class="block mb-2 text-sm font-bold text-gray-700" for="firstName">
                    <%= form.label :edad %>
                  </label>
                  <%= form.text_field :edad ,class: "w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"%>
                </div>
                <div class="md:ml-2">
                  <label class="block mb-2 text-sm font-bold text-gray-700" for="lastName">
                    <%= form.label :esterilizado %>
                  </label>
                  <%= form.text_field :esterilizado , class: "w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"%>
                </div>
              </div>
                
              <div class="mb-6 text-center" class= "w-full px-4 py-2 font-bold text-white bg-blue-500 rounded-full hover:bg-blue-700 focus:outline-none focus:shadow-outline" type= "button" >
                <%= form.submit class:"w-full px-4 py-2 font-bold text-white bg-blue-500 rounded-full hover:bg-blue-700 focus:outline-none focus:shadow-outline" %>
              </div>
              <hr class="mb-6 border-t" />
            <% end %>
					</div>
				</div>
			</div>
		</div>
	</body>

app/views/species/edit.html.erb
<h1>Editing Species</h1>

<%= render 'form', species: @species %>

<%= link_to 'Show', @species %> |
<%= link_to 'Back', species_index_path %>

app/views/species/index.html.erb
<body class="bg-gray-100 font-sans leading-normal tracking-normal">
    <!--Container-->
    <div class="container w-full mx-auto pt-20">

      <nav class="bg-white border-gray-200 dark:bg-gray-900">
            <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl px-4 md:px-6 py-2.5">
                <a href="https://flowbite.com" class="flex items-center">
                    <img src="https://flowbite.com/docs/images/logo.svg" class="h-6 mr-3 sm:h-9" alt="Flowbite Logo" />
                    <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Mascota</span>
                </a>
            </div>
        </nav>
        <nav class="bg-gray-50 dark:bg-gray-700">
            <div class="max-w-screen-xl px-4 py-3 mx-auto md:px-6">
                <div class="flex items-center">
                    <ul class="flex flex-row mt-0 mr-6 space-x-8 text-sm font-medium">
                        <li>
                            <%= link_to "Mascotas", pets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                        </li>
                        <li>
                            <%= link_to 'Especies', species_index_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                        </li>
                       
                        
                    </ul>
                </div>
            </div>
        </nav>

        <div class="w-full px-4 md:px-0 md:mt-8 mb-16 text-gray-800 leading-normal">

          <div class="flex flex-col">
            <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                  <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                   <%= link_to 'Registra Una Especie', new_species_path %>
                  </button>
                  </a>
                  <table class="min-w-full text-center">
                    <thead class="border-b bg-gray-800">
                      <tr>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          #
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Vterinaria
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Dueño
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Nombre
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Especie
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Mostrar
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Editar
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Eliminar
                        </th>
                      </tr>
                    </thead class="border-b">
                    <tbody>
                      <p id="notice"><%= notice %></p>
                      <% @species.each do |specie| %>
                        <tr class="bg-white border-b">
                          <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">1</td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= specie.raza %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= specie.genero %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= specie.edad %>
                          </td>
                           <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= specie.esterilizado %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= link_to 'Show', specie %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= link_to 'Edit this pet', edit_pet_path(specie), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                           <%= button_to 'Destroy this pet', pet_path(specie), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
                          </td>
                        </tr class="bg-white border-b">
                      <% end %>  
                    </tbody>
                  </table>
                </div>
              </div>
  </div>
</div>

app/views/species/new.html.erb
<%= render 'form', species: @species %>

app/views/species/show.html.erb
<body class="bg-gray-100 font-sans leading-normal tracking-normal">
    <!--Container-->
    <div class="container w-full mx-auto pt-20">

        <div class="w-full px-4 md:px-0 md:mt-8 mb-16 text-gray-800 leading-normal">

          <div class="flex flex-col">
            <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                  <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    <%= link_to 'New Location', new_location_path %>
                  </button>
                  <table class="min-w-full text-center">
                    <thead class="border-b bg-gray-800">
                      <tr>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          #
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Raza
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Genero
                        </th>
                         <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Edad
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Esterilizado
                        </th>
                      </tr>
                    </thead class="border-b">
                    <tbody>
                      <p id="notice"><%= notice %></p>
                        <tr class="bg-white border-b">
                          <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">1</td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= @species.raza %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= @species.raza %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= @species.edad %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= @species.esterilizado %>
                          </td>
  
                        </tr class="bg-white border-b">
                    </tbody>
                  </table>
                </div>
              </div>
  </div>
</div>

            <!--Console Content-->

            
          

            <!--Divider-->
            <hr class="border-b-2 border-gray-400 my-8 mx-4">
             <button class="ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium">
              <%= link_to 'Editar', edit_species_path(@species),  class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"  %>
            </button>

            <button class="ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium">
              <%= button_to 'Eliminar', species_path(@species), method: :delete,  class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"  %>
            </button>

            <button class="ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium">
            <%= link_to 'Atras', species_index_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
            </button>

            <!--/ Console Content-->

        </div>


    </div>
    <!--/container-->

    <script>
    /*Toggle dropdown list*/
    /*https://gist.github.com/slavapas/593e8e50cf4cc16ac972afcbad4f70c8*/

    var userMenuDiv = document.getElementById("userMenu");
    var userMenu = document.getElementById("userButton");

    var navMenuDiv = document.getElementById("nav-content");
    var navMenu = document.getElementById("nav-toggle");

    document.onclick = check;

    function check(e) {
        var target = (e && e.target) || (event && event.srcElement);

        //User Menu
        if (!checkParent(target, userMenuDiv)) {
            // click NOT on the menu
            if (checkParent(target, userMenu)) {
                // click on the link
                if (userMenuDiv.classList.contains("invisible")) {
                    userMenuDiv.classList.remove("invisible");
                } else { userMenuDiv.classList.add("invisible"); }
            } else {
                // click both outside link and outside menu, hide menu
                userMenuDiv.classList.add("invisible");
            }
        }

        //Nav Menu
        if (!checkParent(target, navMenuDiv)) {
            // click NOT on the menu
            if (checkParent(target, navMenu)) {
                // click on the link
                if (navMenuDiv.classList.contains("hidden")) {
                    navMenuDiv.classList.remove("hidden");
                } else { navMenuDiv.classList.add("hidden"); }
            } else {
                // click both outside link and outside menu, hide menu
                navMenuDiv.classList.add("hidden");
            }
        }

    }

    function checkParent(t, elm) {
        while (t.parentNode) {
            if (t == elm) { return true; }
            t = t.parentNode;
        }
        return false;
    }
    </script>

</body>

</html>