config/routes.rb
Rails.application.routes.draw do
  resources :medicals
  resources :medical_histories
  resources :diaries
  resources :specialities
  resources :pets
  resources :test2s
  root 'static_pages#index'
  resources :species
  resources :responsibles
  resources :locations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :medical
  belongs_to :pet
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :pacient
end

app/models/medical.rb
class Medical < ApplicationRecord
  belongs_to :speciality
end

app/models/medical_history.rb
class MedicalHistory < ApplicationRecord
  belongs_to :diary
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :location
  belongs_to :responsible
  belongs_to :species
end

app/models/responsible.rb
class Responsible < ApplicationRecord
    has_many :pacient
end

app/models/speciality.rb
class Speciality < ApplicationRecord
  belongs_to :location
end

app/models/species.rb
class Species < ApplicationRecord
    has_many :pacient
end

app/models/test2.rb
class Test2 < ApplicationRecord
  belongs_to :location
  belongs_to :responsible
  belongs_to :species
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: %i[ show edit update destroy ]

  # GET /diaries or /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1 or /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries or /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to diary_url(@diary), notice: "Diary was successfully created." }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1 or /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to diary_url(@diary), notice: "Diary was successfully updated." }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1 or /diaries/1.json
  def destroy
    @diary.destroy

    respond_to do |format|
      format.html { redirect_to diaries_url, notice: "Diary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def diary_params
      params.require(:diary).permit(:medical_id, :pet_id, :horario, :fecha)
    end
end

app/controllers/medicals_controller.rb
class MedicalsController < ApplicationController
  before_action :set_medical, only: %i[ show edit update destroy ]

  # GET /medicals or /medicals.json
  def index
    @medicals = Medical.all
  end

  # GET /medicals/1 or /medicals/1.json
  def show
  end

  # GET /medicals/new
  def new
    @medical = Medical.new
  end

  # GET /medicals/1/edit
  def edit
  end

  # POST /medicals or /medicals.json
  def create
    @medical = Medical.new(medical_params)

    respond_to do |format|
      if @medical.save
        format.html { redirect_to medical_url(@medical), notice: "Medical was successfully created." }
        format.json { render :show, status: :created, location: @medical }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicals/1 or /medicals/1.json
  def update
    respond_to do |format|
      if @medical.update(medical_params)
        format.html { redirect_to medical_url(@medical), notice: "Medical was successfully updated." }
        format.json { render :show, status: :ok, location: @medical }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicals/1 or /medicals/1.json
  def destroy
    @medical.destroy

    respond_to do |format|
      format.html { redirect_to medicals_url, notice: "Medical was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medical
      @medical = Medical.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medical_params
      params.require(:medical).permit(:speciality_id, :nombre, :telefono, :direccion_residencia)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]

  # GET /pets or /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1 or /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:location_id, :responsible_id, :species_id, :nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/medicals_helper.rb
module MedicalsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

app/helpers/specialities_helper.rb
module SpecialitiesHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/test2s_helper.rb
module Test2sHelper
end

app/views/medicals/_form.html.erb
<%= form_with(model: medical, class: "contents") do |form| %>
  <% if medical.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(medical.errors.count, "error") %> prohibited this medical from being saved:</h2>

      <ul>
        <% medical.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :speciality_id %>
    <%= form.text_field :speciality_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :telefono %>
    <%= form.text_field :telefono, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :direccion_residencia %>
    <%= form.text_field :direccion_residencia, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/medicals/_medical.html.erb
<body class="bg-gray-100 font-sans leading-normal tracking-normal">
    <!--Container-->
    <div class="container w-full mx-auto pt-20">

        <div class="w-full px-4 md:px-0 md:mt-8 mb-16 text-gray-800 leading-normal">

          <div class="flex flex-col">
            <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                  <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    <%= link_to 'Nuevo Medico', new_medical_path %>
                  </button>
                  <table class="min-w-full text-center">
                    <thead class="border-b bg-gray-800">
                      <tr>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          #
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Especialidad
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Nombre
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Telefono
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Direccion
                        </th>
                      </tr>
                    </thead class="border-b">
                    <tbody>
                      <p id="notice"><%= notice %></p>
                        <tr class="bg-white border-b">
                          <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"> <%= medical.id %></td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= medical.speciality.nombre %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= medical.nombre %>
                          </td>
                           <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= medical.telefono %>
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <%= medical.direccion_residencia %>
                          </td>
  
                        </tr class="bg-white border-b">
                    </tbody>
                  </table>
                </div>
              </div>
  </div>
</div>

            <!--Console Content-->

            
          

            <!--Divider-->
            <hr class="border-b-2 border-gray-400 my-8 mx-4">

            <!--/ Console Content-->

        </div>


    </div>
    <!--/container-->

    <script>
    /*Toggle dropdown list*/
    /*https://gist.github.com/slavapas/593e8e50cf4cc16ac972afcbad4f70c8*/

    var userMenuDiv = document.getElementById("userMenu");
    var userMenu = document.getElementById("userButton");

    var navMenuDiv = document.getElementById("nav-content");
    var navMenu = document.getElementById("nav-toggle");

    document.onclick = check;

    function check(e) {
        var target = (e && e.target) || (event && event.srcElement);

        //User Menu
        if (!checkParent(target, userMenuDiv)) {
            // click NOT on the menu
            if (checkParent(target, userMenu)) {
                // click on the link
                if (userMenuDiv.classList.contains("invisible")) {
                    userMenuDiv.classList.remove("invisible");
                } else { userMenuDiv.classList.add("invisible"); }
            } else {
                // click both outside link and outside menu, hide menu
                userMenuDiv.classList.add("invisible");
            }
        }

        //Nav Menu
        if (!checkParent(target, navMenuDiv)) {
            // click NOT on the menu
            if (checkParent(target, navMenu)) {
                // click on the link
                if (navMenuDiv.classList.contains("hidden")) {
                    navMenuDiv.classList.remove("hidden");
                } else { navMenuDiv.classList.add("hidden"); }
            } else {
                // click both outside link and outside menu, hide menu
                navMenuDiv.classList.add("hidden");
            }
        }

    }

    function checkParent(t, elm) {
        while (t.parentNode) {
            if (t == elm) { return true; }
            t = t.parentNode;
        }
        return false;
    }
    </script>

</body>

</html>

app/views/medicals/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing medical</h1>

  <%= render "form", medical: @medical %>

  <%= link_to "Show this medical", @medical, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to medicals", medicals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/medicals/index.html.erb
<body class="bg-gray-100 font-sans leading-normal tracking-normal">
<!--Container-->
    <div class="container w-full mx-auto pt-20">

        <nav class="bg-white border-gray-200 dark:bg-gray-900">
            <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl px-4 md:px-6 py-2.5">
                <a href="https://flowbite.com" class="flex items-center">
                    <img src="https://flowbite.com/docs/images/logo.svg" class="h-6 mr-3 sm:h-9" alt="Flowbite Logo" />
                    <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Medicos</span>
                </a>
            </div>
        </nav>
        <nav class="bg-gray-50 dark:bg-gray-700">
            <div class="max-w-screen-xl px-4 py-3 mx-auto md:px-6">
                <div class="flex items-center">
                    <ul class="flex flex-row mt-0 mr-6 space-x-8 text-sm font-medium">
                        <li>
                            <%= link_to "Especialidades", specialities_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                        </li>
                        <li>
                            <%= link_to 'Historial Medico', medical_histories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                        </li>
                        <li>
                            <%= link_to 'Diario', diaries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>


    <div class="w-full px-4 md:px-0 md:mt-8 mb-16 text-gray-800 leading-normal">

      <div class="flex flex-col">
        <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
            <div class="overflow-hidden">
              <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
               <%= link_to 'Registra Un Medico', new_medical_path %>
              </button>
              </a>
              <table class="min-w-full text-center">
                <thead class="border-b bg-gray-800">
                  <tr>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      #
                    </th>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      Calendario ID
                    </th>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      Motivo
                    </th>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      Diagnostico
                    </th>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      Tratamiento
                    </th>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      Mostrar
                    </th>
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                      Editar
                    </th>
                  </tr>
                </thead class="border-b">
                <tbody>
                  <p id="notice"><%= notice %></p>
                  <% @medicals.each do |medical| %>
                    <tr class="bg-white border-b">
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= medical.id %></td>
                      <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                        <%= medical.speciality.nombre %>
                      </td>
                      <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                        <%= medical.nombre %>
                      </td>
                      <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                        <%= medical.telefono %>
                      </td>
                       <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                        <%= medical.direccion_residencia %>
                      </td>
                      <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                        <%= link_to 'Mostrar', medical, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                      </td>
                      <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                        <%= link_to 'Editar', edit_pet_path(medical), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                      </td>
                  
                    </tr class="bg-white border-b">
                  <% end %>  
                </tbody>
              </table>
            </div>
          </div>
</div>
</div>

app/views/medicals/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New medical</h1>

  <%= render "form", medical: @medical %>

  <%= link_to 'Back to medicals', medicals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/medicals/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @medical %>

    <%= link_to 'Edit this medical', edit_medical_path(@medical), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this medical', medical_path(@medical), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to medicals', medicals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>